---
# tasks file for gcp-basic-installations

- name: download and extract the installation files
  unarchive:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.key }}"
    group: "{{ item.key }}"
    remote_src: yes
  with_dict: "{{ installation }}"  
