---
# tasks file for gcp-basic-installations

# configurations for .....

- name: download and extract the installation files
  unarchive:
    src: https://ftp.itu.edu.tr/Mirror/Apache/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz
    dest: /hadoop-3.2.1
    owner: hadoop
    remote_src: yes
- name: update config files ve upload
- name: run the .....