---
# tasks file for gcp-basic-installations

# configurations for .....

- name: download and extract the installation files
  unarchive:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.key }}"
    remote_src: yes
  with_dict: "{{ installation }}"  
# - name: update config files and upload
# - name: run the .....